### ISSUE TITLE
Docker - Error using the API in Docker

### ISSUE THREAD

**Issue by app-generator** [app-generator/api-server-django#7]
**Set up** - follow the README instructions

> Get the code

```bash
$ git clone https://github.com/app-generator/api-server-django.git
$ cd api-server-django
```

> Start the app in Docker

```bash
$ docker-compose up -d --build
```

The Build log ends without errors but the API is not available on port `5000`

![image](https://user-images.githubusercontent.com/51070104/126251057-bca813b4-828a-4344-9dc6-ea7cedc5d003.png)

**Comment by koladev32** [comment]
Alright. 

Please, which type of OS  are you using? 

Also, can you send an output of  `docker-compose logs` to better inspect the issues?

**Comment by app-generator** [comment]
Tests ok. Closing.
Ty @koladev32
