### ISSUE TITLE
Enabling /admin fails on authentication

### ISSUE THREAD

**Issue by andrelopesmrx** [app-generator/api-server-django#9]
User model (and auth) used in the backend seems to break the default django /admin,

How to reproduce:

1 enable /admin in core/urls.py:
```
from django.contrib import admin # <-- added 
from django.urls import include, path

urlpatterns = [
    path("api/users/", include(("api.routers", "api"), namespace="api")),
    path('admin/', admin.site.urls),  # <-- added
]
```

2 create super user:
```
$ python manage.py createsuperuser --email "marx@labmice.nl" --username "marx"
Password: 
Password (again): 
Superuser created successfully.
```

3 Frontend login works fine http://xyz:3000/authentication/sign-in

4 Backendlogin http://xyz:5000/admin fails with message:
Please enter the correct email and password for a staff account. Note that both fields may be case-sensitive.

No exception or errors are thrown in the backend console (even with DEBUG enabled).

**Comment by app-generator** [comment]
@koladev32 please take a look at this use case. 
Ty

**Comment by koladev32** [comment]
Hi @andrelopesmrx 

It means that the `is_staff` attribute concerning the user is `False` actually.

A simple solution will be to connect to the Django shell or database and set the `is_staff` attribute to `True`.

I've also checked the code, and there is a typo in the `create_superuser` method of the `UserManager`. The correction of this typo will eventually resolve the bug.

```python
# api/user/models.py
    def create_superuser(self, username, email, password):
        """
        Create and return a `User` with superuser (admin) permissions.
        """
        ...
        user.is_superuser = True
        user.is_staff = True # => this line
        user.save(using=self._db)

        return user
```
The attribute is not existent in the `User` model.

 I've just added it at [https://github.com/app-generator/api-server-django/commit/60515c368326a18f0ed3b13dae98ed34369f3f31](https://github.com/app-generator/api-server-django/commit/60515c368326a18f0ed3b13dae98ed34369f3f31) and also added the migrations at [https://github.com/app-generator/api-server-django/commit/51c6503bfbdc4ff1435e263afb05b7ab284a429a](https://github.com/app-generator/api-server-django/commit/51c6503bfbdc4ff1435e263afb05b7ab284a429a), so the issues should not resurface again. Please, let me know how it goes.

**Comment by andrelopesmrx** [comment]
Hi @koladev32,
Thanks for your help with it, I replicated the fix in my codebase, and I confirmed it worked.
